# Generated by Django 3.1.7 on 2021-04-01 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sberbank', '0002_add_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={'ordering': ['-created'], 'verbose_name': 'log entry', 'verbose_name_plural': 'log entries'},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='details',
        ),
    ]
